env:
  action_frequency: 60              # (int): environment executes action at the action_frequency rate
  physics_frequency: 60             # (int): physics frequency (1 / physics_timestep for physx)
  device: null                      # (None or str): specifies the device to be used if running on the gpu with torch backend

render:
  viewer_width: 1280
  viewer_height: 720

scene:
  type: Scene

robots: []

objects: []

task:
  type: DummyTask
